# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - golint
    - gomnd
    - ifshort
    - interfacer
    - lll
    - maligned
    - paralleltest
    - scopelint
    - testpackage
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - funlen
        - goconst
        - goerr113
        - gomnd
        - noctx
      path: "_test.go"
