// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpmock

import (
	"net/http"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.nhat.io/httpmock"
)

// NewExpectation creates a new instance of Expectation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpectation(t interface {
	mock.TestingT
	Cleanup(func())
}) *Expectation {
	mock := &Expectation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Expectation is an autogenerated mock type for the expectation type
type Expectation struct {
	mock.Mock
}

type Expectation_Expecter struct {
	mock *mock.Mock
}

func (_m *Expectation) EXPECT() *Expectation_Expecter {
	return &Expectation_Expecter{mock: &_m.Mock}
}

// After provides a mock function for the type Expectation
func (_mock *Expectation) After(d time.Duration) httpmock.Expectation {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for After")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(time.Duration) httpmock.Expectation); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_After_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'After'
type Expectation_After_Call struct {
	*mock.Call
}

// After is a helper method to define mock.On call
//   - d time.Duration
func (_e *Expectation_Expecter) After(d any) *Expectation_After_Call {
	return &Expectation_After_Call{Call: _e.mock.On("After", d)}
}

func (_c *Expectation_After_Call) Run(run func(d time.Duration)) *Expectation_After_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_After_Call) Return(expectation httpmock.Expectation) *Expectation_After_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_After_Call) RunAndReturn(run func(d time.Duration) httpmock.Expectation) *Expectation_After_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type Expectation
func (_mock *Expectation) Handle(w http.ResponseWriter, r *http.Request, defaultHeaders map[string]string) error {
	ret := _mock.Called(w, r, defaultHeaders)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, map[string]string) error); ok {
		r0 = returnFunc(w, r, defaultHeaders)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Expectation_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Expectation_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - defaultHeaders map[string]string
func (_e *Expectation_Expecter) Handle(w any, r any, defaultHeaders any) *Expectation_Handle_Call {
	return &Expectation_Handle_Call{Call: _e.mock.On("Handle", w, r, defaultHeaders)}
}

func (_c *Expectation_Handle_Call) Run(run func(w http.ResponseWriter, r *http.Request, defaultHeaders map[string]string)) *Expectation_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Expectation_Handle_Call) Return(err error) *Expectation_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Expectation_Handle_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, defaultHeaders map[string]string) error) *Expectation_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Once provides a mock function for the type Expectation
func (_mock *Expectation) Once() httpmock.Expectation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Once")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func() httpmock.Expectation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_Once_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Once'
type Expectation_Once_Call struct {
	*mock.Call
}

// Once is a helper method to define mock.On call
func (_e *Expectation_Expecter) Once() *Expectation_Once_Call {
	return &Expectation_Once_Call{Call: _e.mock.On("Once")}
}

func (_c *Expectation_Once_Call) Run(run func()) *Expectation_Once_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_Once_Call) Return(expectation httpmock.Expectation) *Expectation_Once_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_Once_Call) RunAndReturn(run func() httpmock.Expectation) *Expectation_Once_Call {
	_c.Call.Return(run)
	return _c
}

// Return provides a mock function for the type Expectation
func (_mock *Expectation) Return(v any) httpmock.Expectation {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Return")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(any) httpmock.Expectation); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_Return_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Return'
type Expectation_Return_Call struct {
	*mock.Call
}

// Return is a helper method to define mock.On call
//   - v any
func (_e *Expectation_Expecter) Return(v any) *Expectation_Return_Call {
	return &Expectation_Return_Call{Call: _e.mock.On("Return", v)}
}

func (_c *Expectation_Return_Call) Run(run func(v any)) *Expectation_Return_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_Return_Call) Return(expectation httpmock.Expectation) *Expectation_Return_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_Return_Call) RunAndReturn(run func(v any) httpmock.Expectation) *Expectation_Return_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnCode provides a mock function for the type Expectation
func (_mock *Expectation) ReturnCode(code int) httpmock.Expectation {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for ReturnCode")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(int) httpmock.Expectation); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_ReturnCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnCode'
type Expectation_ReturnCode_Call struct {
	*mock.Call
}

// ReturnCode is a helper method to define mock.On call
//   - code int
func (_e *Expectation_Expecter) ReturnCode(code any) *Expectation_ReturnCode_Call {
	return &Expectation_ReturnCode_Call{Call: _e.mock.On("ReturnCode", code)}
}

func (_c *Expectation_ReturnCode_Call) Run(run func(code int)) *Expectation_ReturnCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_ReturnCode_Call) Return(expectation httpmock.Expectation) *Expectation_ReturnCode_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_ReturnCode_Call) RunAndReturn(run func(code int) httpmock.Expectation) *Expectation_ReturnCode_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnFile provides a mock function for the type Expectation
func (_mock *Expectation) ReturnFile(filePath string) httpmock.Expectation {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ReturnFile")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(string) httpmock.Expectation); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_ReturnFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnFile'
type Expectation_ReturnFile_Call struct {
	*mock.Call
}

// ReturnFile is a helper method to define mock.On call
//   - filePath string
func (_e *Expectation_Expecter) ReturnFile(filePath any) *Expectation_ReturnFile_Call {
	return &Expectation_ReturnFile_Call{Call: _e.mock.On("ReturnFile", filePath)}
}

func (_c *Expectation_ReturnFile_Call) Run(run func(filePath string)) *Expectation_ReturnFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_ReturnFile_Call) Return(expectation httpmock.Expectation) *Expectation_ReturnFile_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_ReturnFile_Call) RunAndReturn(run func(filePath string) httpmock.Expectation) *Expectation_ReturnFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnHeader provides a mock function for the type Expectation
func (_mock *Expectation) ReturnHeader(header string, value string) httpmock.Expectation {
	ret := _mock.Called(header, value)

	if len(ret) == 0 {
		panic("no return value specified for ReturnHeader")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(string, string) httpmock.Expectation); ok {
		r0 = returnFunc(header, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_ReturnHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnHeader'
type Expectation_ReturnHeader_Call struct {
	*mock.Call
}

// ReturnHeader is a helper method to define mock.On call
//   - header string
//   - value string
func (_e *Expectation_Expecter) ReturnHeader(header any, value any) *Expectation_ReturnHeader_Call {
	return &Expectation_ReturnHeader_Call{Call: _e.mock.On("ReturnHeader", header, value)}
}

func (_c *Expectation_ReturnHeader_Call) Run(run func(header string, value string)) *Expectation_ReturnHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Expectation_ReturnHeader_Call) Return(expectation httpmock.Expectation) *Expectation_ReturnHeader_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_ReturnHeader_Call) RunAndReturn(run func(header string, value string) httpmock.Expectation) *Expectation_ReturnHeader_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnHeaders provides a mock function for the type Expectation
func (_mock *Expectation) ReturnHeaders(headers httpmock.Header) httpmock.Expectation {
	ret := _mock.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for ReturnHeaders")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(httpmock.Header) httpmock.Expectation); ok {
		r0 = returnFunc(headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_ReturnHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnHeaders'
type Expectation_ReturnHeaders_Call struct {
	*mock.Call
}

// ReturnHeaders is a helper method to define mock.On call
//   - headers httpmock.Header
func (_e *Expectation_Expecter) ReturnHeaders(headers any) *Expectation_ReturnHeaders_Call {
	return &Expectation_ReturnHeaders_Call{Call: _e.mock.On("ReturnHeaders", headers)}
}

func (_c *Expectation_ReturnHeaders_Call) Run(run func(headers httpmock.Header)) *Expectation_ReturnHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 httpmock.Header
		if args[0] != nil {
			arg0 = args[0].(httpmock.Header)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_ReturnHeaders_Call) Return(expectation httpmock.Expectation) *Expectation_ReturnHeaders_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_ReturnHeaders_Call) RunAndReturn(run func(headers httpmock.Header) httpmock.Expectation) *Expectation_ReturnHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnJSON provides a mock function for the type Expectation
func (_mock *Expectation) ReturnJSON(body any) httpmock.Expectation {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for ReturnJSON")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(any) httpmock.Expectation); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_ReturnJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnJSON'
type Expectation_ReturnJSON_Call struct {
	*mock.Call
}

// ReturnJSON is a helper method to define mock.On call
//   - body any
func (_e *Expectation_Expecter) ReturnJSON(body any) *Expectation_ReturnJSON_Call {
	return &Expectation_ReturnJSON_Call{Call: _e.mock.On("ReturnJSON", body)}
}

func (_c *Expectation_ReturnJSON_Call) Run(run func(body any)) *Expectation_ReturnJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_ReturnJSON_Call) Return(expectation httpmock.Expectation) *Expectation_ReturnJSON_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_ReturnJSON_Call) RunAndReturn(run func(body any) httpmock.Expectation) *Expectation_ReturnJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Returnf provides a mock function for the type Expectation
func (_mock *Expectation) Returnf(format string, args ...any) httpmock.Expectation {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Returnf")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(string, ...any) httpmock.Expectation); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_Returnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Returnf'
type Expectation_Returnf_Call struct {
	*mock.Call
}

// Returnf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *Expectation_Expecter) Returnf(format any, args ...any) *Expectation_Returnf_Call {
	return &Expectation_Returnf_Call{Call: _e.mock.On("Returnf",
		append([]any{format}, args...)...)}
}

func (_c *Expectation_Returnf_Call) Run(run func(format string, args ...any)) *Expectation_Returnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Expectation_Returnf_Call) Return(expectation httpmock.Expectation) *Expectation_Returnf_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_Returnf_Call) RunAndReturn(run func(format string, args ...any) httpmock.Expectation) *Expectation_Returnf_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type Expectation
func (_mock *Expectation) Run(handle func(r *http.Request) ([]byte, error)) httpmock.Expectation {
	ret := _mock.Called(handle)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(func(r *http.Request) ([]byte, error)) httpmock.Expectation); ok {
		r0 = returnFunc(handle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Expectation_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - handle func(r *http.Request) ([]byte, error)
func (_e *Expectation_Expecter) Run(handle any) *Expectation_Run_Call {
	return &Expectation_Run_Call{Call: _e.mock.On("Run", handle)}
}

func (_c *Expectation_Run_Call) Run(run func(handle func(r *http.Request) ([]byte, error))) *Expectation_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(r *http.Request) ([]byte, error)
		if args[0] != nil {
			arg0 = args[0].(func(r *http.Request) ([]byte, error))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_Run_Call) Return(expectation httpmock.Expectation) *Expectation_Run_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_Run_Call) RunAndReturn(run func(handle func(r *http.Request) ([]byte, error)) httpmock.Expectation) *Expectation_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Times provides a mock function for the type Expectation
func (_mock *Expectation) Times(i uint) httpmock.Expectation {
	ret := _mock.Called(i)

	if len(ret) == 0 {
		panic("no return value specified for Times")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(uint) httpmock.Expectation); ok {
		r0 = returnFunc(i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_Times_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Times'
type Expectation_Times_Call struct {
	*mock.Call
}

// Times is a helper method to define mock.On call
//   - i uint
func (_e *Expectation_Expecter) Times(i any) *Expectation_Times_Call {
	return &Expectation_Times_Call{Call: _e.mock.On("Times", i)}
}

func (_c *Expectation_Times_Call) Run(run func(i uint)) *Expectation_Times_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_Times_Call) Return(expectation httpmock.Expectation) *Expectation_Times_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_Times_Call) RunAndReturn(run func(i uint) httpmock.Expectation) *Expectation_Times_Call {
	_c.Call.Return(run)
	return _c
}

// Twice provides a mock function for the type Expectation
func (_mock *Expectation) Twice() httpmock.Expectation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Twice")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func() httpmock.Expectation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_Twice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Twice'
type Expectation_Twice_Call struct {
	*mock.Call
}

// Twice is a helper method to define mock.On call
func (_e *Expectation_Expecter) Twice() *Expectation_Twice_Call {
	return &Expectation_Twice_Call{Call: _e.mock.On("Twice")}
}

func (_c *Expectation_Twice_Call) Run(run func()) *Expectation_Twice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_Twice_Call) Return(expectation httpmock.Expectation) *Expectation_Twice_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_Twice_Call) RunAndReturn(run func() httpmock.Expectation) *Expectation_Twice_Call {
	_c.Call.Return(run)
	return _c
}

// UnlimitedTimes provides a mock function for the type Expectation
func (_mock *Expectation) UnlimitedTimes() httpmock.Expectation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UnlimitedTimes")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func() httpmock.Expectation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_UnlimitedTimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlimitedTimes'
type Expectation_UnlimitedTimes_Call struct {
	*mock.Call
}

// UnlimitedTimes is a helper method to define mock.On call
func (_e *Expectation_Expecter) UnlimitedTimes() *Expectation_UnlimitedTimes_Call {
	return &Expectation_UnlimitedTimes_Call{Call: _e.mock.On("UnlimitedTimes")}
}

func (_c *Expectation_UnlimitedTimes_Call) Run(run func()) *Expectation_UnlimitedTimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_UnlimitedTimes_Call) Return(expectation httpmock.Expectation) *Expectation_UnlimitedTimes_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_UnlimitedTimes_Call) RunAndReturn(run func() httpmock.Expectation) *Expectation_UnlimitedTimes_Call {
	_c.Call.Return(run)
	return _c
}

// WaitUntil provides a mock function for the type Expectation
func (_mock *Expectation) WaitUntil(w <-chan time.Time) httpmock.Expectation {
	ret := _mock.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for WaitUntil")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(<-chan time.Time) httpmock.Expectation); ok {
		r0 = returnFunc(w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_WaitUntil_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitUntil'
type Expectation_WaitUntil_Call struct {
	*mock.Call
}

// WaitUntil is a helper method to define mock.On call
//   - w <-chan time.Time
func (_e *Expectation_Expecter) WaitUntil(w any) *Expectation_WaitUntil_Call {
	return &Expectation_WaitUntil_Call{Call: _e.mock.On("WaitUntil", w)}
}

func (_c *Expectation_WaitUntil_Call) Run(run func(w <-chan time.Time)) *Expectation_WaitUntil_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 <-chan time.Time
		if args[0] != nil {
			arg0 = args[0].(<-chan time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_WaitUntil_Call) Return(expectation httpmock.Expectation) *Expectation_WaitUntil_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_WaitUntil_Call) RunAndReturn(run func(w <-chan time.Time) httpmock.Expectation) *Expectation_WaitUntil_Call {
	_c.Call.Return(run)
	return _c
}

// WithBody provides a mock function for the type Expectation
func (_mock *Expectation) WithBody(body any) httpmock.Expectation {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for WithBody")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(any) httpmock.Expectation); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_WithBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithBody'
type Expectation_WithBody_Call struct {
	*mock.Call
}

// WithBody is a helper method to define mock.On call
//   - body any
func (_e *Expectation_Expecter) WithBody(body any) *Expectation_WithBody_Call {
	return &Expectation_WithBody_Call{Call: _e.mock.On("WithBody", body)}
}

func (_c *Expectation_WithBody_Call) Run(run func(body any)) *Expectation_WithBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_WithBody_Call) Return(expectation httpmock.Expectation) *Expectation_WithBody_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_WithBody_Call) RunAndReturn(run func(body any) httpmock.Expectation) *Expectation_WithBody_Call {
	_c.Call.Return(run)
	return _c
}

// WithBodyJSON provides a mock function for the type Expectation
func (_mock *Expectation) WithBodyJSON(v any) httpmock.Expectation {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for WithBodyJSON")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(any) httpmock.Expectation); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_WithBodyJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithBodyJSON'
type Expectation_WithBodyJSON_Call struct {
	*mock.Call
}

// WithBodyJSON is a helper method to define mock.On call
//   - v any
func (_e *Expectation_Expecter) WithBodyJSON(v any) *Expectation_WithBodyJSON_Call {
	return &Expectation_WithBodyJSON_Call{Call: _e.mock.On("WithBodyJSON", v)}
}

func (_c *Expectation_WithBodyJSON_Call) Run(run func(v any)) *Expectation_WithBodyJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_WithBodyJSON_Call) Return(expectation httpmock.Expectation) *Expectation_WithBodyJSON_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_WithBodyJSON_Call) RunAndReturn(run func(v any) httpmock.Expectation) *Expectation_WithBodyJSON_Call {
	_c.Call.Return(run)
	return _c
}

// WithBodyf provides a mock function for the type Expectation
func (_mock *Expectation) WithBodyf(format string, args ...any) httpmock.Expectation {
	var _ca []any
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WithBodyf")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(string, ...any) httpmock.Expectation); ok {
		r0 = returnFunc(format, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_WithBodyf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithBodyf'
type Expectation_WithBodyf_Call struct {
	*mock.Call
}

// WithBodyf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *Expectation_Expecter) WithBodyf(format any, args ...any) *Expectation_WithBodyf_Call {
	return &Expectation_WithBodyf_Call{Call: _e.mock.On("WithBodyf",
		append([]any{format}, args...)...)}
}

func (_c *Expectation_WithBodyf_Call) Run(run func(format string, args ...any)) *Expectation_WithBodyf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Expectation_WithBodyf_Call) Return(expectation httpmock.Expectation) *Expectation_WithBodyf_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_WithBodyf_Call) RunAndReturn(run func(format string, args ...any) httpmock.Expectation) *Expectation_WithBodyf_Call {
	_c.Call.Return(run)
	return _c
}

// WithHeader provides a mock function for the type Expectation
func (_mock *Expectation) WithHeader(header string, value any) httpmock.Expectation {
	ret := _mock.Called(header, value)

	if len(ret) == 0 {
		panic("no return value specified for WithHeader")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(string, any) httpmock.Expectation); ok {
		r0 = returnFunc(header, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_WithHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithHeader'
type Expectation_WithHeader_Call struct {
	*mock.Call
}

// WithHeader is a helper method to define mock.On call
//   - header string
//   - value any
func (_e *Expectation_Expecter) WithHeader(header any, value any) *Expectation_WithHeader_Call {
	return &Expectation_WithHeader_Call{Call: _e.mock.On("WithHeader", header, value)}
}

func (_c *Expectation_WithHeader_Call) Run(run func(header string, value any)) *Expectation_WithHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Expectation_WithHeader_Call) Return(expectation httpmock.Expectation) *Expectation_WithHeader_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_WithHeader_Call) RunAndReturn(run func(header string, value any) httpmock.Expectation) *Expectation_WithHeader_Call {
	_c.Call.Return(run)
	return _c
}

// WithHeaders provides a mock function for the type Expectation
func (_mock *Expectation) WithHeaders(headers map[string]any) httpmock.Expectation {
	ret := _mock.Called(headers)

	if len(ret) == 0 {
		panic("no return value specified for WithHeaders")
	}

	var r0 httpmock.Expectation
	if returnFunc, ok := ret.Get(0).(func(map[string]any) httpmock.Expectation); ok {
		r0 = returnFunc(headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpmock.Expectation)
		}
	}
	return r0
}

// Expectation_WithHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithHeaders'
type Expectation_WithHeaders_Call struct {
	*mock.Call
}

// WithHeaders is a helper method to define mock.On call
//   - headers map[string]any
func (_e *Expectation_Expecter) WithHeaders(headers any) *Expectation_WithHeaders_Call {
	return &Expectation_WithHeaders_Call{Call: _e.mock.On("WithHeaders", headers)}
}

func (_c *Expectation_WithHeaders_Call) Run(run func(headers map[string]any)) *Expectation_WithHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]any
		if args[0] != nil {
			arg0 = args[0].(map[string]any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Expectation_WithHeaders_Call) Return(expectation httpmock.Expectation) *Expectation_WithHeaders_Call {
	_c.Call.Return(expectation)
	return _c
}

func (_c *Expectation_WithHeaders_Call) RunAndReturn(run func(headers map[string]any) httpmock.Expectation) *Expectation_WithHeaders_Call {
	_c.Call.Return(run)
	return _c
}
