// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package planner

import (
	mock "github.com/stretchr/testify/mock"
	"go.nhat.io/httpmock/matcher"
)

// NewExpectation creates a new instance of Expectation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpectation(t interface {
	mock.TestingT
	Cleanup(func())
}) *Expectation {
	mock := &Expectation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Expectation is an autogenerated mock type for the Expectation type
type Expectation struct {
	mock.Mock
}

type Expectation_Expecter struct {
	mock *mock.Mock
}

func (_m *Expectation) EXPECT() *Expectation_Expecter {
	return &Expectation_Expecter{mock: &_m.Mock}
}

// BodyMatcher provides a mock function for the type Expectation
func (_mock *Expectation) BodyMatcher() *matcher.BodyMatcher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BodyMatcher")
	}

	var r0 *matcher.BodyMatcher
	if returnFunc, ok := ret.Get(0).(func() *matcher.BodyMatcher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*matcher.BodyMatcher)
		}
	}
	return r0
}

// Expectation_BodyMatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BodyMatcher'
type Expectation_BodyMatcher_Call struct {
	*mock.Call
}

// BodyMatcher is a helper method to define mock.On call
func (_e *Expectation_Expecter) BodyMatcher() *Expectation_BodyMatcher_Call {
	return &Expectation_BodyMatcher_Call{Call: _e.mock.On("BodyMatcher")}
}

func (_c *Expectation_BodyMatcher_Call) Run(run func()) *Expectation_BodyMatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_BodyMatcher_Call) Return(bodyMatcher *matcher.BodyMatcher) *Expectation_BodyMatcher_Call {
	_c.Call.Return(bodyMatcher)
	return _c
}

func (_c *Expectation_BodyMatcher_Call) RunAndReturn(run func() *matcher.BodyMatcher) *Expectation_BodyMatcher_Call {
	_c.Call.Return(run)
	return _c
}

// Fulfilled provides a mock function for the type Expectation
func (_mock *Expectation) Fulfilled() {
	_mock.Called()
	return
}

// Expectation_Fulfilled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fulfilled'
type Expectation_Fulfilled_Call struct {
	*mock.Call
}

// Fulfilled is a helper method to define mock.On call
func (_e *Expectation_Expecter) Fulfilled() *Expectation_Fulfilled_Call {
	return &Expectation_Fulfilled_Call{Call: _e.mock.On("Fulfilled")}
}

func (_c *Expectation_Fulfilled_Call) Run(run func()) *Expectation_Fulfilled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_Fulfilled_Call) Return() *Expectation_Fulfilled_Call {
	_c.Call.Return()
	return _c
}

func (_c *Expectation_Fulfilled_Call) RunAndReturn(run func()) *Expectation_Fulfilled_Call {
	_c.Run(run)
	return _c
}

// FulfilledTimes provides a mock function for the type Expectation
func (_mock *Expectation) FulfilledTimes() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FulfilledTimes")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// Expectation_FulfilledTimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FulfilledTimes'
type Expectation_FulfilledTimes_Call struct {
	*mock.Call
}

// FulfilledTimes is a helper method to define mock.On call
func (_e *Expectation_Expecter) FulfilledTimes() *Expectation_FulfilledTimes_Call {
	return &Expectation_FulfilledTimes_Call{Call: _e.mock.On("FulfilledTimes")}
}

func (_c *Expectation_FulfilledTimes_Call) Run(run func()) *Expectation_FulfilledTimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_FulfilledTimes_Call) Return(v uint) *Expectation_FulfilledTimes_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Expectation_FulfilledTimes_Call) RunAndReturn(run func() uint) *Expectation_FulfilledTimes_Call {
	_c.Call.Return(run)
	return _c
}

// HeaderMatcher provides a mock function for the type Expectation
func (_mock *Expectation) HeaderMatcher() matcher.HeaderMatcher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HeaderMatcher")
	}

	var r0 matcher.HeaderMatcher
	if returnFunc, ok := ret.Get(0).(func() matcher.HeaderMatcher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matcher.HeaderMatcher)
		}
	}
	return r0
}

// Expectation_HeaderMatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderMatcher'
type Expectation_HeaderMatcher_Call struct {
	*mock.Call
}

// HeaderMatcher is a helper method to define mock.On call
func (_e *Expectation_Expecter) HeaderMatcher() *Expectation_HeaderMatcher_Call {
	return &Expectation_HeaderMatcher_Call{Call: _e.mock.On("HeaderMatcher")}
}

func (_c *Expectation_HeaderMatcher_Call) Run(run func()) *Expectation_HeaderMatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_HeaderMatcher_Call) Return(headerMatcher matcher.HeaderMatcher) *Expectation_HeaderMatcher_Call {
	_c.Call.Return(headerMatcher)
	return _c
}

func (_c *Expectation_HeaderMatcher_Call) RunAndReturn(run func() matcher.HeaderMatcher) *Expectation_HeaderMatcher_Call {
	_c.Call.Return(run)
	return _c
}

// Method provides a mock function for the type Expectation
func (_mock *Expectation) Method() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Expectation_Method_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method'
type Expectation_Method_Call struct {
	*mock.Call
}

// Method is a helper method to define mock.On call
func (_e *Expectation_Expecter) Method() *Expectation_Method_Call {
	return &Expectation_Method_Call{Call: _e.mock.On("Method")}
}

func (_c *Expectation_Method_Call) Run(run func()) *Expectation_Method_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_Method_Call) Return(s string) *Expectation_Method_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Expectation_Method_Call) RunAndReturn(run func() string) *Expectation_Method_Call {
	_c.Call.Return(run)
	return _c
}

// RemainTimes provides a mock function for the type Expectation
func (_mock *Expectation) RemainTimes() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemainTimes")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// Expectation_RemainTimes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemainTimes'
type Expectation_RemainTimes_Call struct {
	*mock.Call
}

// RemainTimes is a helper method to define mock.On call
func (_e *Expectation_Expecter) RemainTimes() *Expectation_RemainTimes_Call {
	return &Expectation_RemainTimes_Call{Call: _e.mock.On("RemainTimes")}
}

func (_c *Expectation_RemainTimes_Call) Run(run func()) *Expectation_RemainTimes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_RemainTimes_Call) Return(v uint) *Expectation_RemainTimes_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Expectation_RemainTimes_Call) RunAndReturn(run func() uint) *Expectation_RemainTimes_Call {
	_c.Call.Return(run)
	return _c
}

// URIMatcher provides a mock function for the type Expectation
func (_mock *Expectation) URIMatcher() matcher.Matcher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for URIMatcher")
	}

	var r0 matcher.Matcher
	if returnFunc, ok := ret.Get(0).(func() matcher.Matcher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matcher.Matcher)
		}
	}
	return r0
}

// Expectation_URIMatcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URIMatcher'
type Expectation_URIMatcher_Call struct {
	*mock.Call
}

// URIMatcher is a helper method to define mock.On call
func (_e *Expectation_Expecter) URIMatcher() *Expectation_URIMatcher_Call {
	return &Expectation_URIMatcher_Call{Call: _e.mock.On("URIMatcher")}
}

func (_c *Expectation_URIMatcher_Call) Run(run func()) *Expectation_URIMatcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Expectation_URIMatcher_Call) Return(matcher1 matcher.Matcher) *Expectation_URIMatcher_Call {
	_c.Call.Return(matcher1)
	return _c
}

func (_c *Expectation_URIMatcher_Call) RunAndReturn(run func() matcher.Matcher) *Expectation_URIMatcher_Call {
	_c.Call.Return(run)
	return _c
}
